### ISSUE TITLE
"Data too long for column 'id' at row 1 using placeholders and params and sql function

### ISSUE THREAD

**Issue by adrianboston** [silviucpp/mysql_pool#2]
mysql_pool:query(pid, <<"INSERT INTO table (column1, column2, column3), (?,?,?)">>, [<<"UNHEX(\"8588d8d02ade11e88708acbc328f652b\")">>,null,1]

Fails with
"Data too long for column 'id' at row 1. See AnsiCode 22001"

Same command but this time the UNHEX function is not a param (but other two remain params)

mysql_pool:query(pid, <<"INSERT INTO table (column1, column2, column3), (UNHEX(\"8588d8d02ade11e88708acbc328f652b\">,?,?)">>, [null,1]

success?!!

**Comment by zuiderkwast** [comment]
The first example is an Erlang syntax error, but if you escape the quotes inside the string such as `<<"UNHEX(\"8588d8d02ade11e88708acbc328f652b\")">>`, then this is a binary (string) that you send to the server as the first param. It column1 would be a VARCHAR or TEXT, this text could be stored, but it is not a function call as you might want. You would have to do the UNHEX function in Erlang.

In the second example, the UNHEX is an SQL function that is called when the query is executed so the results is an integer.

If you want to convert a binary containing a hexadecimal number to an integer in Erlang, you can do it like this:

```Erlang
1> binary_to_integer(<<"8588d8d02ade11e88708acbc328f652b">>, 16).
177497873305353575895536269948525438251
```

**Comment by silviucpp** [comment]
@zuiderkwast  Thanks for answering!

**Comment by adrianboston** [comment]
The first example held escaped quotes but I failed to copy verbatim so it did actually resemble your one:

mysql_pool:query(pid, <<"INSERT INTO table (column1, column2, column3), (?,?,?)">>, [<<"UNHEX(\"8588d8d02ade11e88708acbc328f652b\")">>,null,1]

Nevertheless, the point about a param vs a function is taken.  Thanks.

The above was an issue on the path to the real problem:
Which is passing a string with escaped quotes -- not in the column1 that does use a UNHEX function -- but into column2. Currently, Im not using '?' style params and it fails on mysql escaped sequences.

mysql_pool:query(pid, <<"INSERT INTO table (column1, column2, column3) VALUES (UNHEX(\"8588d8d02ade11e88708acbc328f652b\"), "A string containing \"quotes\"", 1 ]


What would be your suggested solution. I'm thinking the internal encode/2 on strings?!

Thanks

**Comment by zuiderkwast** [comment]
Yes, mysql:encode/2 (https://mysql-otp.github.io/mysql-otp/mysql.html#encode-2)

For this you need the connection pid, so you can do use mysql_pool:with/1:

```Erlang
mysql_pool:with(pool_name,
                fun (Pid) ->
                    Query = [<<"INSERT INTO table (column1, column2, column3)"
                                " VALUES (UNHEX(\"8588d8d02ade11e88708acbc328f652b\"), ">>,
                             mysql:encode(Pid, "A string containing \"quotes\" or 'quotes'"),
                             <<", 1>>],
                    mysql:query(Pid, Query)
                end)
```

**Comment by zuiderkwast** [comment]
Actually, in standard SQL, strings are quoted with single quotes and a single quote is escaped by repeating the single quote, not backslash. Double quotes and backslash escape is just a MySQL-specific extension (bug or feature) which can be turned off in the server configuration. I suggest using single quotes in SQL string literals to stick to the SQL standards.

**Comment by adrianboston** [comment]
Its a string passed on by the user/client. Hmm. to bounce or not to bounce. Good point. Thanks.

**Comment by zuiderkwast** [comment]
Bounce? Any string can be safely sent to the db using `?` or `mysql:encode/2`. No need to worry about what characters are in it.
