### ISSUE TITLE
error with ssl connection to tidbcloud

### ISSUE THREAD

**Issue by redgreat** [silviucpp/mysql_pool#9]
erlang: 26.2.1
mysql_pool: master

when i start up with rebar3 shell

 [error] gen_server <0.639.0> terminated with reason: {error,{1105,<<"HY000">>,<<"Connections using insecure transport are prohibited. See https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters">>}}

config:
{mysql_pool, [
    {pools, [
      {pool_tidb, [
          {size, 5},
          {connection_options, [
              {host, "xxx"},
              {user, "root"},
              {port, 4000},
              {password, "123"},
              {database, "dbdb"},
              {ssl_ca, [{server_name_indication, disable},
              {cacertfile, "/etc/ssl/cert.pem"},
              {versions, ['tlsv1.2']}]}
          ]}
        ]}
    ]}
  ]}

start method:
in my _app.erl
start(_StartType, _StartArgs) ->
    mysql_pool:start(),
   xxx

**Comment by redgreat** [comment]
im sorry i wrote the wrong config.

**Comment by silviucpp** [comment]
:)) Today I was starting looking to tidb architecture . What a coincidence !
